######################################################################
# Automatically generated by qmake (2.01a) pt. kwi 24 03:06:44 2015
######################################################################

OBJECTS_DIR=./obj
INCLUDEPATH=inc
MOC_DIR=./moc
QT+=widgets
QMAKE_CXXFLAGS+=-std=c++11
TEMPLATE = app
TARGET = ciecz
DEPENDPATH += src inc
INCLUDEPATH += . inc

# Input
HEADERS += inc/ciecz.hh
SOURCES += src/ciecz.cpp
