#############################################################################
# Makefile for building: symulacja_cieczy
# Generated by qmake (2.01a) (Qt 4.8.6) on: czw. cze 4 22:09:34 2015
# Project:  pro/symulacja_cieczy.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile.app pro/symulacja_cieczy.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -std=c++11 -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -Ipro -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -Iinc -Ipro -I./ui/inc -Ipro -Iinc -Imoc -Iui/inc -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/czasteczka.cpp \
		src/dmainwindow.cpp \
		src/main.cpp \
		src/okno_glowne.cpp \
		src/simulation.cpp \
		src/zbiornik.cpp moc/moc_okno_glowne.cpp \
		moc/moc_zbiornik.cpp \
		moc/moc_dmainwindow.cpp
OBJECTS       = obj/czasteczka.o \
		obj/dmainwindow.o \
		obj/main.o \
		obj/okno_glowne.o \
		obj/simulation.o \
		obj/zbiornik.o \
		obj/moc_okno_glowne.o \
		obj/moc_zbiornik.o \
		obj/moc_dmainwindow.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		pro/symulacja_cieczy.pro
QMAKE_TARGET  = symulacja_cieczy
DESTDIR       = 
TARGET        = symulacja_cieczy

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile.app $(TARGET)

$(TARGET): ui/inc/ui_dmainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile.app: pro/symulacja_cieczy.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile.app pro/symulacja_cieczy.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile.app pro/symulacja_cieczy.pro

dist: 
	@$(CHK_DIR_EXISTS) obj/symulacja_cieczy1.0.0 || $(MKDIR) obj/symulacja_cieczy1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) obj/symulacja_cieczy1.0.0/ && $(COPY_FILE) --parents inc/czasteczka.hh inc/flagi.hh inc/kolor.hh inc/okno_glowne.hh inc/vector.hh inc/zbiornik.hh inc/dmainwindow.h obj/symulacja_cieczy1.0.0/ && $(COPY_FILE) --parents src/czasteczka.cpp src/dmainwindow.cpp src/main.cpp src/okno_glowne.cpp src/simulation.cpp src/zbiornik.cpp obj/symulacja_cieczy1.0.0/ && $(COPY_FILE) --parents ui/dmainwindow.ui obj/symulacja_cieczy1.0.0/ && (cd `dirname obj/symulacja_cieczy1.0.0` && $(TAR) symulacja_cieczy1.0.0.tar symulacja_cieczy1.0.0 && $(COMPRESS) symulacja_cieczy1.0.0.tar) && $(MOVE) `dirname obj/symulacja_cieczy1.0.0`/symulacja_cieczy1.0.0.tar.gz . && $(DEL_FILE) -r obj/symulacja_cieczy1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile.app


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc/moc_okno_glowne.cpp moc/moc_zbiornik.cpp moc/moc_dmainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc/moc_okno_glowne.cpp moc/moc_zbiornik.cpp moc/moc_dmainwindow.cpp
moc/moc_okno_glowne.cpp: inc/flagi.hh \
		inc/kolor.hh \
		inc/czasteczka.hh \
		inc/vector.hh \
		inc/zbiornik.hh \
		inc/dmainwindow.h \
		inc/okno_glowne.hh
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) inc/okno_glowne.hh -o moc/moc_okno_glowne.cpp

moc/moc_zbiornik.cpp: inc/flagi.hh \
		inc/czasteczka.hh \
		inc/kolor.hh \
		inc/vector.hh \
		inc/zbiornik.hh
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) inc/zbiornik.hh -o moc/moc_zbiornik.cpp

moc/moc_dmainwindow.cpp: inc/dmainwindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) inc/dmainwindow.h -o moc/moc_dmainwindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: ui/inc/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) ui/inc/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui/inc/ui_dmainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui/inc/ui_dmainwindow.h
ui/inc/ui_dmainwindow.h: ui/dmainwindow.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic ui/dmainwindow.ui -o ui/inc/ui_dmainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

obj/czasteczka.o: src/czasteczka.cpp inc/czasteczka.hh \
		inc/kolor.hh \
		inc/vector.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/czasteczka.o src/czasteczka.cpp

obj/dmainwindow.o: src/dmainwindow.cpp inc/dmainwindow.h \
		ui/inc/ui_dmainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/dmainwindow.o src/dmainwindow.cpp

obj/main.o: src/main.cpp inc/okno_glowne.hh \
		inc/flagi.hh \
		inc/kolor.hh \
		inc/czasteczka.hh \
		inc/vector.hh \
		inc/zbiornik.hh \
		inc/dmainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o src/main.cpp

obj/okno_glowne.o: src/okno_glowne.cpp inc/okno_glowne.hh \
		inc/flagi.hh \
		inc/kolor.hh \
		inc/czasteczka.hh \
		inc/vector.hh \
		inc/zbiornik.hh \
		inc/dmainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/okno_glowne.o src/okno_glowne.cpp

obj/simulation.o: src/simulation.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/simulation.o src/simulation.cpp

obj/zbiornik.o: src/zbiornik.cpp inc/zbiornik.hh \
		inc/flagi.hh \
		inc/czasteczka.hh \
		inc/kolor.hh \
		inc/vector.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/zbiornik.o src/zbiornik.cpp

obj/moc_okno_glowne.o: moc/moc_okno_glowne.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_okno_glowne.o moc/moc_okno_glowne.cpp

obj/moc_zbiornik.o: moc/moc_zbiornik.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_zbiornik.o moc/moc_zbiornik.cpp

obj/moc_dmainwindow.o: moc/moc_dmainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_dmainwindow.o moc/moc_dmainwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

