/* generated by dia/codegen.py */
/*(NULL)*/
class Zbiornik 
{
public:
	Zbiornik (double szerokosc,
	          double wysokosc,
	          int ilosc_czasteczek);
	double maksymalnaPojemnosc ();
	double pojemnoscAktualna ();
	void dodajCzasteczke ();
	Czasteczka usunCzasteczke ();
	void wypiszZawartosc ();
	double& szerokosc ();
	double szerokosc ();
	double& wysokosc ();
	double wysokosc ();
	int ilosc_czasteczek ();
	list<Czasteczka>& czasteczki ();
private:
	double _szerokosc;
	double _wysokosc;
	int _ilosc_czasteczek;
	list<Czasteczka> _czasteczki;
};

/*(NULL)*/
class Wektor 
{
public:
	Wektor dodaj (const Wektor& a,
	              const Wektor& b);
	Wektor odejmij (const Wektor& a,
	                const Wektor& b);
	Wektor pomnoz (const Wektor& a,
	               const Wektor& b);
	Wektor (double x,
	        double y);
	Wektor ();
	double& x ();
	double x ();
	double& y ();
	double y ();
private:
	double _x;
	double _y;
};

/*(NULL)*/
class PanelSterowania 
{
public:
	void play ();
	void pause ();
	void stop ();
	void dodajZbiornik ();
	Zbiornik usunZbiornik ();
	string& plik_testowy ();
	string plik_testowy ();
	int ilosc_zbiornikow ();
	list<Zbiornik>& zbiorniki ();
private:
	string _plik_testowy;
	int _ilosc_zbiornikow;
	list<Zbiornik> _zbiorniki;
};

/*(NULL)*/
class Czasteczka 
{
public:
	list stworzNCzasteczek (int ilosc);
	Czasteczka (double promien,
	            double lepkosc,
	            double gestosc,
	            Wektor polozenie,
	            string kolor);
	Czasteczka ();
	double& promien ();
	double promien ();
	double& lepkosc ();
	double lepkosc ();
	double& gestosc ();
	double gestosc ();
	Wektor& polozenie ();
	Wektor polozenie ();
	string& kolor ();
	string kolor ();
private:
	double _promien;
	double _lepkosc;
	double _gestosc;
	Wektor _polozenie;
	string _kolor;
};

